document.writeln("<nav class=\'footer\'>");
document.writeln("				<div class=\'footer-content clearfix\'>");
document.writeln("					<p class=\'brand\'></p>");
document.writeln("					<ul>");
document.writeln("						<li class=\'title\'>关于我们</li>");
document.writeln("						<li><a href=\'#\'>公司介绍</a></li>");
document.writeln("						<li><a href=\'#\'>业务模式</a></li>");
document.writeln("						<li><a href=\'#\'>合作机构</a></li>");
document.writeln("						<li><a href=\'#\'>服务协议</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul>");
document.writeln("						<li class=\'title\'>合作公司</li>");
document.writeln("						<li><a href=\'#\'>公司介绍</a></li>");
document.writeln("						<li><a href=\'#\'>业务模式</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul>");
document.writeln("						<li class=\'title\'>联系我们</li>");
document.writeln("						<li><a href=\'#\'>公司介绍</a></li>");
document.writeln("						<li><a href=\'#\'>业务模式</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul>");
document.writeln("						<li class=\'title\'>找到我们</li>");
document.writeln("						<li><a href=\'#\'>地址</a></li>");
document.writeln("						<li><a href=\'#\'>电话</a></li>");
document.writeln("");
document.writeln("					</ul>");
document.writeln("					<ul>");
document.writeln("						<li class=\'title\'>国家政策</li>");
document.writeln("						<li><a href=\'#\'>地址</a></li>");
document.writeln("						<li><a href=\'#\'>网页</a></li>");
document.writeln("");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</nav>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<!--页脚-->");
document.writeln("		<footer>");
document.writeln("			<ul>");
document.writeln("				<li><span class=\'icon icon-zfywxk\'>支付业务许可</span></li>");
document.writeln("				<li><span class=\'icon icon-pcirk\'>PCI认证</span></li>");
document.writeln("				<li><span class=\'icon icon-visayz\'>VISA认证</span></li>");
document.writeln("				<li><span class=\'icon icon-vsjmfw\'>网络工商</span></li>");
document.writeln("				<li><span class=\'icon icon-wlgs\'>网络工商</span></li>");
document.writeln("				<li><span class=\'icon icon-rzcx\'>网络工商</span></li>");
document.writeln("				<li><span class=\'icon icon-gs\'>网络工商</span></li>");
document.writeln("			</ul>");
document.writeln("			<p>杭州红杏资本投资公司 版权所有 © 2018-2020</p>");
document.writeln("		</footer>");