document.writeln("<head>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\' />");
document.writeln("		<!--强制IE最高版本加载-->");
document.writeln("		<title>红杏资本投资网站</title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'css/normalize.css\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'css/main.css\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'js/vendor/OwlCarousel2-2.3.4/assets/owl.carousel.min.css\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'js/vendor/OwlCarousel2-2.3.4/assets/owl.theme.default.min.css\'>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--[if lte IE8]>	");
document.writeln("		<![endif]-->");
document.writeln("		<header>");
document.writeln("			<nav class=\'top\'>");
document.writeln("				<span class=\'tel\'>理财热线：400-888-8888</span>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>登录</a></li>");
document.writeln("					<li><a href=\'#\'>快速注册</a></li>");
document.writeln("					<li><a href=\'#\'>关于</a></li>");
document.writeln("					<li><a href=\'#\'>帮助</a></li>");
document.writeln("					<li><a href=\'#\'>APP下载</a></li>");
document.writeln("				</ul>");
document.writeln("			</nav>");
document.writeln("			<nav class=\'main\'>");
document.writeln("				<a href=\'#\' class=\'brand\'><img src=\'img/logo.png\' alt=\'回到首页\' /></a>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>首页</a></li>");
document.writeln("					<li><a href=\'#\'>理财频道</a></li>");
document.writeln("					<li><a href=\'#\'>投资频道</a></li>");
document.writeln("					<li><a href=\'#\'>新手专区</a></li>");
document.writeln("					<li><a href=\'#\'>安全保障</a></li>");
document.writeln("				</ul>");
document.writeln("			</nav>");
document.writeln("		</header>");
document.writeln("		<!--中间部分-->");
document.writeln("		<div class=\'container\'>");
document.writeln("			<section class=\'transaction\'>");
document.writeln("				<div class=\'trans-content\'>");
document.writeln("					<div class=\'trans-data\'>");
document.writeln("						<span>平台累计成交金额</span>");
document.writeln("						<span class=\'trans-money\'>19888</span>");
document.writeln("						<span>万元</span>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'trans-content\'>");
document.writeln("					<div class=\'trans-data\'>");
document.writeln("						<span>过去七日成交金额</span>");
document.writeln("						<span class=\'trans-money\'>1888</span>");
document.writeln("						<span>万元</span>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'trans-report\'>");
document.writeln("					<a href=\'#\'>查看平台运营报告</a>");
document.writeln("				</div>");
document.writeln("			</section>");