package cn.edu.hzvtc.entity;
// Generated Apr 28, 2019 12:38:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Caritem generated by hbm2java
 */
@Entity
@Table(name = "caritem", catalog = "rac")
public class CartItem implements java.io.Serializable {

	private int id;
	private Product product;
	private Integer number;
	private Integer sum;

	public CartItem() {
	}

	public CartItem(int id) {
		this.id = id;
	}

	public CartItem(int id, Product product, Integer number, Integer sum) {
		this.id = id;
		this.product = product;
		this.number = number;
		this.sum = sum;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "SUM")
	public Integer getSum() {
		return number * product.getPrice();
	}
	
	//手动计算出来
	public void setSum(Integer sum) {
		this.sum = sum;
	}


}
