package cn.edu.hzvtc.entity;
// Generated Apr 23, 2019 9:45:27 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "rac")
public class Department implements java.io.Serializable {

	private Integer id;
	private String departmentName;
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Employee> employees_1 = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(String departmentName, Set<Employee> employees, Set<Employee> employees_1) {
		this.departmentName = departmentName;
		this.employees = employees;
		this.employees_1 = employees_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DEPARTMENT_NAME")
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employee> getEmployees_1() {
		return this.employees_1;
	}

	public void setEmployees_1(Set<Employee> employees_1) {
		this.employees_1 = employees_1;
	}

}
