package cn.edu.hzvtc.entity;
// Generated Apr 28, 2019 12:38:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "rac")
public class Product implements java.io.Serializable {

	private int id;
	private String name;
	private Integer price;
	private String description;
	private Integer status;

	private Set<CartItem> caritems = new HashSet<CartItem>(0);

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, String name, Integer price, String description,Integer status, Set<CartItem> caritems) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.status = status;
		this.description = description;
		this.caritems = caritems;
	}



	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRICE")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<CartItem> getCaritems() {
		return this.caritems;
	}

	public void setCaritems(Set<CartItem> caritems) {
		this.caritems = caritems;
	}

}
