package cn.edu.hzvtc.entity;
// Generated Apr 28, 2019 12:38:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "rac")
public class User implements java.io.Serializable {

	private Integer id;
	private String password;
	private String name;
	private String phone;
	private String email;
	private String actualname;
	private String address;


	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}

	public User(String password, String name, String phone, String email, String actualname ,String address ) {
		this.password = password;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.actualname = actualname;
		this.address = address;

	}

	public User(String password, String name, String phone, String email, String actualname,String address, Set<Order> orders) {

		this.password = password;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.actualname = actualname;
		this.address = address;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PASSWORD", nullable = false, length = 19)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}



	@Column(name = "ACTUALNAME", nullable = false)
	public String getActualname() {
		return this.actualname;
	}

	public void setActualname(String actualname) {
		this.actualname = actualname;
	}




	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
